### ISSUE TITLE
[Request] Ability to only partially replace bedrock

### ISSUE THREAD

**Issue by charlesbevans** [The-Fireplace-Minecraft-Mods/Bedrock-Replacer#1]
I'd like to use world drop to have players mine down to the bottom and go into the Beneath and then mine down to get to the nether, but I need some bedrock for other mods, like Embers. Is there any chance of getting the option to only replace the highest or lowest layer of bedrock (whichever is easier). Players can go looking for a place to dig through. (I can probably work around the nether ceiling if I have to.)
Edit: Saw a typo. I'm asking for a boon and I can at least show the respect of typing like a grown up. :)

**Comment by The-Fireplace** [comment]
It was done a little bit ago, with the bedrock replacement percentage. I don't recall  exactly what mod version I did it in, but it was probably a more recent one.
